##################################################################################################
# Emp_Mgmt services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: employee-mgmt
  labels:
    app: employee-mgmt
    service: employee-mgmt
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: employee-mgmt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: employee-mgmt-info
  labels:
    account: employee-mgmt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "reasonForChange"
  name: employee-mgmt-v1
  labels:
    app: employee-mgmt
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-mgmt
      version: v1
  template:
    metadata:
      labels:
        app: employee-mgmt
        version: v1
    spec:
      serviceAccountName: employee-mgmt-info
      containers:
      - name: employee-mgmt
        image: demoapp2020/emp-mgmt:latest
        imagePullPolicy: Always
        env:
        - name: _JAVA_OPTIONS 
          value: "-Xmx512m -Xms256m"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod,swagger"
        #- name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
        #  value: true
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/jhipster_demo"
        - name: JHIPSTER_SLEEP
          value: "30" 
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      imagePullSecrets:
      - name: emp-mgmt-secret
      volumes:
      - name: tmp
        emptyDir: {}

